GraphsChart/Controllers/ChartsController.cs
using System.Collections.Generic;
using System.Web.Mvc;


namespace GraphsChart.Controllers
{
    public class ChartsController : Controller
    {
        // GET: Charts
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Chartjs()
        {

            return View("ChartJs");
        }
        public ActionResult GoogleChart()
        {
            return View("GoogleChart");
        }

        public ActionResult Morris()
        {
            return View("Morris");
        }



    }
}

GraphsChart/Views/Charts/ChartJs.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChartJs</title>
</head>
<body>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <h2>Charts Js Example </h2>

    <div class="col-md-12">
  


            <div class="row">
                <div class="col-md-4">
                    <canvas id="canvas1" width="10" height="10"></canvas>
                </div>
                <div class="col-md-4">
                    <canvas id="canvas2" width="10" height="10"></canvas>
                </div>

                <div class="col-md-4">
                    <canvas id="LineCanvas"></canvas>

            
            </div>
        </div>
    </div>

    <br />
    <hr />

    <div class="container-fluid">
        <div class="row">

            <div class="col-md-4">
                <canvas id="doubleLine" width="10" height="10"></canvas>
            </div>
            <div class="col-md-4">
                <canvas id="donut" width="10" height="10"></canvas>
            </div>
            <div class="col-md-4">
                <canvas id="canvas3"></canvas>

            </div>
        </div>

    </div>


@*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@
    <script src="~/assets/js/CustomCharts/ChartJs.js"></script>
    <script src="~/Scripts/jquery-3.1.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="~/assets/plugins/ChartjsBundle/Chart.bundle.js"></script>
    <script src="~/assets/plugins/ChartjsBundle/Chart.PieceLabel.js"></script>
    <script src="~/assets/plugins/ChartjsBundle/Chart.PieceLabel.min.js"></script>


    <script>

        //Initalized array with values
        var chartValues1 = [40,70,20,30,50,90,120,30,45,87];             
        var chartValues2 = [121,5,25,15,421,14,45,210,102,59];
        var Lables = ["Lab1", "Lab2", "Lab3", "Lab4", "Lab5", "Lab6", "Lab7", "Lab8", "Lab9", "Lab10"];



    $(document).ready(function() {

 
        //Functions call for chart js
        SingleBarChart_ChartJs(chartValues1, Lables);
        DoubleBarChart_ChartJs(chartValues1,chartValues2, Lables);
        SingleLineChart_ChartJs(chartValues1, Lables);
        DoubleLineChart_ChartJs(chartValues1, chartValues2, Lables);



        PieCharts(chartValues1, Lables);


        doughnut(chartValues2, Lables);



    });






    </script>
</body>
</html>

GraphsChart/Views/Charts/GoogleChart.cshtml
@{
    ViewBag.Title = "GoogleChart";
}

<h2>GoogleChart</h2>

<div class="container">
    <div class="col-md-4" id="myChartDiv" style="height: 450px; width: 700px;"></div>
</div>
<div class="col-md-4" id="myChartDiv4" style="height: 450px; width: 700px;"></div>


<div id="chart_div" style="height: 400px; width: 500px;">

</div>


<div id="chart_div2" style="height: 400px; width: 500px;">

</div>


@*<script src="~/Scripts/jquery-3.1.0.min.js"></script>*@


<script src="~/assets/js/CustomCharts/GoogleCharts.js"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="http://www.google.com/jsapi" type="text/javascript"></script>
<script type="text/javascript">



</script>


<script>
    google.load('visualization', '1', { packages: ['corechart'] });
    google.charts.load('current', { packages: ['corechart', 'line'] });
    //google.charts.setOnLoadCallback(drawChart);

    var chartinfoList = new Object();
    var listLength;
    var chartData;

    $(document).ready(function() {
        //SetChartInfo();
        getValues();

        PieChart_Google(chartinfoList, listLength);
        // BarChart(chartinfoList, listLength);
        debugger;
        BarChart_Google(chartinfoList, listLength);
        LineChart_Google(chartinfoList, listLength);
        //DonutChart_Google(chartinfoList, listLength);

    });


    function getValues() {
        var urlpath = '@Url.Action("BarChart", "Charts")';
        $.ajax({
            url: urlpath,
            dataType: 'json',
            type: "Get",
            async: false,
            success: function(result) {
                for (var i = 0; i < result.length; i++) {

                    chartinfoList[i] = ({ WeekNo: result[i].WeekNo, MaxTemp: result[i].MaxTemp, MinTemp: result[i].MinTemp });
                }

            }

        });

        listLength = Object.keys(chartinfoList).length;

    }


    //function SetChartInfo2(chartinfoList, listLength) {
    //    debugger;

    //    var data = new window.google.visualization.DataTable();
    //    data.addColumn('string', 'Column Name');
    //    data.addColumn('number', 'Column Value');
    //    for (var i = 0; i < listLength; i++) {
    //        data.addRow([chartinfoList[i].WeekNo, chartinfoList[i].MinTemp]);
    //    }
    //    var options = {
    //        title: 'USA City Distribution',
    //        is3D: true
    //    };
    //    new window.google.visualization.PieChart(document.getElementById('myChartDiv')).
    //    draw(data, {
    //        title: "Google Pie Chart"

    //    });


    //}


    //google.setOnLoadCallback(drawChart);

    //function drawChart() {
    //    debugger;
    //    var data = new google.visualization.DataTable();
    //    data.addColumn('string', "Test1");
    //    data.addColumn('number', "Test2");
    //    data.addColumn('number', "Test3");

    //    for (i = 0; i < 4; i++) {
    //        data.addRow([chartinfoList[i].WeekNo, chartinfoList[i].MaxTemp, chartinfoList[i].MinTemp]);
    //    }
    //    var options = {
    //        title: 'Sale and Purchase Compare',
    //        hAxis: { title: "asd", titleTextStyle: { color: 'red'} }
    //    };

    //    var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
    //    chart.draw(data, options);
    //}


</script>

GraphsChart/Views/Charts/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Graph Charts Implementations</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>


    <hr/>

<div class="container">
    <div class="row">
        <div class="col-md-3"><button class="btn btn-info" onclick="location.href = '@Url.Action("Chartjs", "Charts")'">Chart Js</button>
        </div>
        <div class="col-md-3"><button class="btn btn-info" onclick="location.href = '@Url.Action("Morris", "Charts")'">Morries Chart</button>
        </div>
        <div class="col-md-3"><button class="btn btn-info" onclick="location.href = '@Url.Action("GoogleChart", "Charts")'">Google Charts</button>
        </div>
        <div class="col-md-3"><button class="btn btn-info" onclick="location.href = '@Url.Action("Index", "Charts")'">Flot Chart</button>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.1.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

GraphsChart/Views/Charts/Morris.cshtml
@{
    ViewBag.Title = "Morris";

}



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="~/assets/plugins/morriesChart/morris.css" rel="stylesheet"/>
<style>
    .containers {
        max-width: 100%;
    }
</style>
<h2>Morris Chart</h2>


<div class="containers">

    <div class="row">
        <div class="col-md-4">
            <div id="myfirstchart" ></div>

        </div>
        <div class="col-md-4">
            <div id="myfirstchart2" ></div>
        </div>
        <div class="col-md-4">
            <div id="myfirstchart3"></div>
        </div>
    </div>
   
</div>


<hr/>


<div class="containers">

    <div class="row">
        <div class="col-md-4">
            <div id="morrischart1"></div>

        </div>
        <div class="col-md-4">
            <div id="morrischart2"></div>
        </div>
        <div class="col-md-4">
            <div id="morrischart3"></div>
        </div>
    </div>

</div>

<script src="~/Scripts/jquery-3.1.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="~/assets/plugins/morriesChart/raphael-min.js"></script>
<script src="~/assets/plugins/morriesChart/morris.min.js"></script>

<script src="~/assets/js/CustomCharts/MorriesChart.js"></script>
<script type="text/javascript">



</script>


<script>

    var chartData = [];
    var donutchartArray = [];
 
    //var a;
    //var b;
    //var chartLabel = [];
    //var chartValue = [];
    var chartValues1 = [40, 70, 20, 30, 50, 90, 120, 30, 45, 87];
    var chartValues2 = [121, 5, 25, 15, 421, 14, 45, 210, 102, 59];
    var Lables = ["Lab1", "Lab2", "Lab3", "Lab4", "Lab5", "Lab6", "Lab7", "Lab8", "Lab9", "Lab10"];

    $(document).ready(function () {

        //This function is for adding values and label to a array 
        // xLabel represent Chart x axis Label
        // yKeyValue1 and ykeyvalue2 represent Chart y axis Values


        for (var i = 0; i < chartValues1.length; i++) {
            chartData.push({ 'xLabel': Lables[i], 'yKeyvalue1': chartValues1[i], 'yKeyValue2': chartValues2[i] });
        }


        //This function add Values for showing Donut chart
        // do not chage name of 'label' and 'value'
        for (var i = 0; i < chartValues1.length; i++) {
            donutchartArray.push({ 'label': Lables[i], 'value': chartValues2[i] });
        }


    

        //Function Calling to show chart

        DoubleBarChart(chartData, 'myfirstchart', 'xLabel', 'yKeyvalue1', 'yKeyValue2', 'CustomLabelName1', 'CustomLabelName2');
        DoubleLineChart(chartData, 'myfirstchart2', 'xLabel', 'yKeyvalue1', 'yKeyValue2', 'CustomLabelName1', 'CustomLabelName2');
        DoubleAreaChart(chartData, 'myfirstchart3', 'xLabel', 'yKeyvalue1', 'yKeyValue2', 'CustomLabelName1', 'CustomLabelName2');
        DonutChart("morrischart1", donutchartArray);

    });







</script>